[build]
  base = "apps/frontend"
  command = "yarn install --cwd ../.. && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
